Fix migration bundle creation (#133)
After upgrading to `.NET 10` (#131) and updating all the workflow
actions (#132), the migration bundle creation step broke with the
following error:

```
Run dotnet ef migrations bundle --runtime linux-x64 -p ConselvaBudget/ConselvaBudget.csproj -c ConselvaBudgetContext -o /usr/share/dotnet/myapp/migrate-conselvabudget
  dotnet ef migrations bundle --runtime linux-x64 -p ConselvaBudget/ConselvaBudget.csproj -c ConselvaBudgetContext -o /usr/share/dotnet/myapp/migrate-conselvabudget
  shell: /usr/bin/bash -e {0}
  env:
    DOTNET_ROOT: /usr/share/dotnet
Error: /usr/share/dotnet/sdk/10.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(266,5): error NETSDK1047: Assets file '/home/runner/work/conselva-budget/conselva-budget/ConselvaBudget/obj/project.assets.json' doesn't have a target for 'net10.0/linux-x64'. Ensure that restore has run and that you have included 'net10.0' in the TargetFrameworks for your project. You may also need to include 'linux-x64' in your project's RuntimeIdentifiers. [/home/runner/work/conselva-budget/conselva-budget/ConselvaBudget/ConselvaBudget.csproj]
```

This command runs as part of the build process to create an executable
that can migrate the database changes within the production environment.

After some investigation, found out that according to the `dotnet ef
migrations bundle`
[reference](https://learn.microsoft.com/en-us/ef/core/cli/dotnet#dotnet-ef-migrations-bundle),
the correct name for the option to set the target runtime to bundle for
is `--target-runtime <RUNTIME_IDENTIFIER>` or `-r`, not `--runtime` as
per the ASP.NET Core
[tutorial](https://learn.microsoft.com/en-us/azure/app-service/tutorial-dotnetcore-sqldb-app?toc=%2Faspnet%2Fcore%2Ftoc.json&bc=%2Faspnet%2Fcore%2Fbreadcrumb%2Ftoc.json&view=aspnetcore-9.0&tabs=copilot&pivots=azure-portal#4-deploy-sample-code)
that I followed when I first created this.

After testing this change, the bundle creation was successful again.